-- MySQL Script generated by MySQL Workbench
-- Tue Oct  2 08:36:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Locations` (
  `GPSCoordinate` BLOB NOT NULL,
  `LocationName` VARCHAR(45) NOT NULL,
  `Picture` LONGBLOB NULL,
  `Timeline` LONGBLOB NULL,
  `Social_GPSCoordinate` INT NOT NULL,
  `Social_GPSCoordinate1` BLOB NOT NULL,
  PRIMARY KEY (`GPSCoordinate`, `Social_GPSCoordinate`, `Social_GPSCoordinate1`),
  INDEX `fk_Locations_Social1_idx` (`Social_GPSCoordinate1` ASC),
  UNIQUE INDEX `GPSCoordinate_UNIQUE` (`GPSCoordinate` ASC),
  CONSTRAINT `fk_Locations_Social1`
    FOREIGN KEY (`Social_GPSCoordinate1`)
    REFERENCES `mydb`.`Social` (`GPSCoordinate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Social` (
  `GPSCoordinate` BLOB NOT NULL,
  `Ratings` INT NULL,
  `Comments` TEXT(1024) NULL,
  PRIMARY KEY (`GPSCoordinate`),
  UNIQUE INDEX `GPSCoordinate_UNIQUE` (`GPSCoordinate` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `UserNumber` INT NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `CityofResidence` VARCHAR(45) NULL,
  `AboutMe` VARCHAR(45) NULL,
  `LocationsVisited` TINYTEXT NULL,
  `Picture` LONGBLOB NULL,
  `Locations_GPSCoordinate` INT NOT NULL,
  `Locations_Social_GPSCoordinate` INT NOT NULL,
  PRIMARY KEY (`UserNumber`, `Locations_GPSCoordinate`, `Locations_Social_GPSCoordinate`),
  UNIQUE INDEX `UserNumber_UNIQUE` (`UserNumber` ASC),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC),
  INDEX `fk_Users_Locations1_idx` (`Locations_GPSCoordinate` ASC, `Locations_Social_GPSCoordinate` ASC),
  CONSTRAINT `fk_Users_Locations1`
    FOREIGN KEY (`Locations_GPSCoordinate` , `Locations_Social_GPSCoordinate`)
    REFERENCES `mydb`.`Locations` (`GPSCoordinate` , `Social_GPSCoordinate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
