-- MySQL Script generated by MySQL Workbench
-- Wed Oct 24 17:59:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jernigan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jernigan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jernigan` DEFAULT CHARACTER SET utf8 ;
USE `jernigan` ;

-- -----------------------------------------------------
-- Table `jernigan`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jernigan`.`Locations` (
  `LocationID` INT NOT NULL,
  `GPSCoordinate` DECIMAL NOT NULL,
  `LocationName` VARCHAR(45) NOT NULL,
  `Picture` LONGBLOB NULL,
  `Timeline` LONGBLOB NULL,
  `Social_GPSCoordinate` DECIMAL NOT NULL,
  PRIMARY KEY (`LocationID`),
  UNIQUE INDEX `LocationNumber_UNIQUE` (`LocationID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jernigan`.`Social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jernigan`.`Social` (
  `SocialID` INT NOT NULL AUTO_INCREMENT,
  `Rating` INT NULL,
  `Comment` TEXT(1024) NULL,
  `Locations_LocationID` INT NOT NULL,
  PRIMARY KEY (`SocialID`, `Locations_LocationID`),
  INDEX `fk_Social_Locations_idx` (`Locations_LocationID` ASC) VISIBLE,
  CONSTRAINT `fk_Social_Locations`
    FOREIGN KEY (`Locations_LocationID`)
    REFERENCES `jernigan`.`Locations` (`LocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jernigan`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jernigan`.`Users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `CityofResidence` VARCHAR(45) NULL,
  `AboutMe` VARCHAR(8192) NULL,
  `LocationsVisited` TINYTEXT NULL,
  `Picture` LONGBLOB NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserNumber_UNIQUE` (`UserID` ASC) VISIBLE,
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
