CREATE TABLE [dbo].[Users]
(
	[UserId] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[UserName] NVARCHAR(128) NOT NULL,
	[Email] NVARCHAR(128) NOT NULL,
	[Password] NVARCHAR(128) NOT NULL,
	[CityOfResidence] NVARCHAR(256) NOT NULL,
	[AboutMe] NVARCHAR(1024) NULL,
	[Picture] NVARCHAR(MAX) NULL
)
